// <auto-generated />
using System;
using GirlPower.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GirlPower.Migrations
{
    [DbContext(typeof(GirlPowerContext))]
    [Migration("20200531144741_Migracija")]
    partial class Migracija
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GirlPower.Models.Kategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazivKategorije")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kategorija");
                });

            modelBuilder.Entity("GirlPower.Models.Obavijest", b =>
                {
                    b.Property<DateTime>("DatumSlanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("PorukaObavijesti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Posiljalac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Primalac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.ToTable("Obavijest");
                });

            modelBuilder.Entity("GirlPower.Models.Osoba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMailTelefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Osoba");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Osoba");
                });

            modelBuilder.Entity("GirlPower.Models.Poruka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumSlanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Posiljalac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Primlac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TekstPoruke")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UposlenikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UposlenikId");

                    b.ToTable("Poruka");
                });

            modelBuilder.Entity("GirlPower.Models.Tretman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CijenaTretmana")
                        .HasColumnType("float");

                    b.Property<bool>("Izvrsen")
                        .HasColumnType("bit");

                    b.Property<int?>("KategorijaTretmanaId")
                        .HasColumnType("int");

                    b.Property<string>("NazivTretmana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisTretmana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrajanjeTretmana")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategorijaTretmanaId");

                    b.ToTable("Tretman");
                });

            modelBuilder.Entity("GirlPower.Models.Administrator", b =>
                {
                    b.HasBaseType("GirlPower.Models.Osoba");

                    b.HasDiscriminator().HasValue("Administrator");
                });

            modelBuilder.Entity("GirlPower.Models.Klijent", b =>
                {
                    b.HasBaseType("GirlPower.Models.Osoba");

                    b.Property<int>("IdKlijenta")
                        .HasColumnType("int");

                    b.Property<bool>("Registrovan")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Klijent");
                });

            modelBuilder.Entity("GirlPower.Models.Uposlenik", b =>
                {
                    b.HasBaseType("GirlPower.Models.Osoba");

                    b.HasDiscriminator().HasValue("Uposlenik");
                });

            modelBuilder.Entity("GirlPower.Models.Poruka", b =>
                {
                    b.HasOne("GirlPower.Models.Uposlenik", null)
                        .WithMany("Poruke")
                        .HasForeignKey("UposlenikId");
                });

            modelBuilder.Entity("GirlPower.Models.Tretman", b =>
                {
                    b.HasOne("GirlPower.Models.Kategorija", "KategorijaTretmana")
                        .WithMany()
                        .HasForeignKey("KategorijaTretmanaId");
                });
#pragma warning restore 612, 618
        }
    }
}
